Bump rhysd/actionlint from 1.7.4 to 1.7.6

diff --git a/.github/workflows/functional-tests.yml b/.github/workflows/functional-tests.yml
--- a/.github/workflows/functional-tests.yml
+++ b/.github/workflows/functional-tests.yml
@@ -13,6 +13,7 @@ on: # yamllint disable-line rule:truthy
   schedule:
     # Every Friday at 09:00 JST
     - cron: "0 0 * * 5"
+  workflow_dispatch: {}
 
 defaults:
   run:
@@ -20,17 +21,27 @@ defaults:
 
 jobs:
   get-versions:
-    name: Get 5 latest versions
+    name: Get 3 latest versions
     runs-on: ubuntu-latest
     timeout-minutes: 10
     outputs:
       versions: ${{ steps.prepare-list.outputs.versions }}
     steps:
+      - name: Get releases
+        id: github-releases
+        uses: yakubique/github-releases@v1.2
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          repository: "kovetskiy/mark"
+          sort: "desc"
       - name: Prepare list
         id: prepare-list
+        env:
+          RELEASES_AMOUNT: "3"
         run: |
-          url="https://api.github.com/repos/kovetskiy/mark/releases"
-          versions=$(curl -s "${url}" | jq -c '[.[0:5][].tag_name] | . += ["latest"]')
+          versions=$(echo '${{ steps.github-releases.outputs.releases }}' \
+            | jq -c -r --arg n "${RELEASES_AMOUNT}" '.[0:($n | tonumber)] | . += ["latest"]')
           echo "versions=${versions}" >> "$GITHUB_OUTPUT"
   setup-mark:
     name: Setup mark
@@ -51,3 +62,36 @@ jobs:
           version: "${{ matrix.version }}"
       - name: Print version
         run: mark --version
+  test-force:
+    name: Test force
+    runs-on: ubuntu-latest
+    timeout-minutes: 5
+    strategy:
+      fail-fast: false
+      matrix:
+        force: ["true", "false"]
+    steps:
+      - name: Checkout ${{ github.repository }}
+        uses: actions/checkout@v4
+      - name: Setup mark 1
+        id: setup-mark-1
+        uses: ./
+      - name: Setup mark 2
+        id: setup-mark-2
+        uses: ./
+        with:
+          force: ${{ matrix.force }}
+      - name: Test action completion
+        run: |
+          test_equal() {
+            if [ "${2}" != "${3}" ]; then
+              echo "::error title=${1}::Expected: ${3}. Actual: ${2}."
+              exit 1
+            fi
+          }
+          test_equal "Wrong \"installed\" output from setup-mark-1" \
+            "${{ steps.setup-mark-1.outputs.installed }}" \
+            "true"
+          test_equal "Wrong \"installed\" output from setup-mark-2" \
+            "${{ steps.setup-mark-2.outputs.installed }}" \
+            "${{ matrix.force }}"
